/*
 * CityPay Payment API
 *
 *  This CityPay API is a HTTP RESTful payment API used for direct server to server transactional processing. It provides a number of payment mechanisms including: Internet, MOTO, Continuous Authority transaction processing, 3-D Secure decision handling using RFA Secure, Authorisation, Refunding, Pre-Authorisation, Cancellation/Voids and Completion processing. The API is also capable of tokinsed payments using Card Holder Accounts.  ## Compliance and Security Your application will need to adhere to PCI-DSS standards to operate safely and to meet requirements set out by  Visa and MasterCard and the PCI Security Standards Council. These include  * Data must be collected using TLS version 1.2 using [strong cryptography](#enabled-tls-ciphers). We will not accept calls to our API at   lower grade encryption levels. We regularly scan our TLS endpoints for vulnerabilities and perform TLS assessments   as part of our compliance program. * The application must not store sensitive card holder data (CHD) such as the card security code (CSC) or   primary access number (PAN) * The application must not display the full card number on receipts, it is recommended to mask the PAN   and show the last 4 digits. The API will return this for you for ease of receipt creation * If you are developing a website, you will be required to perform regular scans on the network where you host the   application to meet your compliance obligations * You will be required to be PCI Compliant and the application must adhere to the security standard. Further information   is available from [https://www.pcisecuritystandards.org/](https://www.pcisecuritystandards.org/) * The API verifies that the request is for a valid account and originates from a trusted source using the remote IP   address. Our application firewalls analyse data that may be an attempt to break a large number of security common   security vulnerabilities.. 
 *
 * Contact: support@citypay.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using CityPayAPI.Client;
using CityPayAPI.Api;
// uncomment below to import models
//using CityPayAPI.Model;

namespace CityPayAPI.Test.Api
{
    /// <summary>
    ///  Class for testing OperationalAPIFunctions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class OperationalAPIFunctionsTests : IDisposable
    {
        private OperationalAPIFunctions instance;

        public OperationalAPIFunctionsTests()
        {
            instance = new OperationalAPIFunctions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OperationalAPIFunctions
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' OperationalAPIFunctions
            //Assert.IsType<OperationalAPIFunctions>(instance);
        }

        /// <summary>
        /// Test AclCheckRequest
        /// </summary>
        [Fact]
        public void AclCheckRequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AclCheckRequest aclCheckRequest = null;
            //var response = instance.AclCheckRequest(aclCheckRequest);
            //Assert.IsType<AclCheckResponseModel>(response);
        }

        /// <summary>
        /// Test DomainKeyCheckRequest
        /// </summary>
        [Fact]
        public void DomainKeyCheckRequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DomainKeyCheckRequest domainKeyCheckRequest = null;
            //var response = instance.DomainKeyCheckRequest(domainKeyCheckRequest);
            //Assert.IsType<DomainKeyResponse>(response);
        }

        /// <summary>
        /// Test DomainKeyGenRequest
        /// </summary>
        [Fact]
        public void DomainKeyGenRequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DomainKeyRequest domainKeyRequest = null;
            //var response = instance.DomainKeyGenRequest(domainKeyRequest);
            //Assert.IsType<DomainKeyResponse>(response);
        }

        /// <summary>
        /// Test ListMerchantsRequest
        /// </summary>
        [Fact]
        public void ListMerchantsRequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string clientid = null;
            //var response = instance.ListMerchantsRequest(clientid);
            //Assert.IsType<ListMerchantsResponse>(response);
        }

        /// <summary>
        /// Test PingRequest
        /// </summary>
        [Fact]
        public void PingRequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Ping ping = null;
            //var response = instance.PingRequest(ping);
            //Assert.IsType<Acknowledgement>(response);
        }
    }
}
