/*
 * CityPay Payment API
 *
 *  This CityPay API is a HTTP RESTful payment API used for direct server to server transactional processing. It provides a number of payment mechanisms including: Internet, MOTO, Continuous Authority transaction processing, 3-D Secure decision handling using RFA Secure, Authorisation, Refunding, Pre-Authorisation, Cancellation/Voids and Completion processing. The API is also capable of tokinsed payments using Card Holder Accounts.  ## Compliance and Security Your application will need to adhere to PCI-DSS standards to operate safely and to meet requirements set out by  Visa and MasterCard and the PCI Security Standards Council. These include  * Data must be collected using TLS version 1.2 using [strong cryptography](#enabled-tls-ciphers). We will not accept calls to our API at   lower grade encryption levels. We regularly scan our TLS endpoints for vulnerabilities and perform TLS assessments   as part of our compliance program. * The application must not store sensitive card holder data (CHD) such as the card security code (CSC) or   primary access number (PAN) * The application must not display the full card number on receipts, it is recommended to mask the PAN   and show the last 4 digits. The API will return this for you for ease of receipt creation * If you are developing a website, you will be required to perform regular scans on the network where you host the   application to meet your compliance obligations * You will be required to be PCI Compliant and the application must adhere to the security standard. Further information   is available from [https://www.pcisecuritystandards.org/](https://www.pcisecuritystandards.org/) * The API verifies that the request is for a valid account and originates from a trusted source using the remote IP   address. Our application firewalls analyse data that may be an attempt to break a large number of security common   security vulnerabilities. 
 *
 * Contact: support@citypay.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CityPayAPI.Api;
using CityPayAPI.Model;
using CityPayAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CityPayAPI.Test.Model
{
    /// <summary>
    ///  Class for testing TokenRequestModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokenRequestModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TokenRequestModel
        //private TokenRequestModel instance;

        public TokenRequestModelTests()
        {
            // TODO uncomment below to create an instance of TokenRequestModel
            //instance = new TokenRequestModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TokenRequestModel
        /// </summary>
        [Fact]
        public void TokenRequestModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" TokenRequestModel
            //Assert.IsType<TokenRequestModel>(instance);
        }


        /// <summary>
        /// Test the property 'Accountno'
        /// </summary>
        [Fact]
        public void AccountnoTest()
        {
            // TODO unit test for the property 'Accountno'
        }
        /// <summary>
        /// Test the property 'AmountValue'
        /// </summary>
        [Fact]
        public void AmountValueTest()
        {
            // TODO unit test for the property 'AmountValue'
        }
        /// <summary>
        /// Test the property 'Cardholder'
        /// </summary>
        [Fact]
        public void CardholderTest()
        {
            // TODO unit test for the property 'Cardholder'
        }
        /// <summary>
        /// Test the property 'Cart'
        /// </summary>
        [Fact]
        public void CartTest()
        {
            // TODO unit test for the property 'Cart'
        }
        /// <summary>
        /// Test the property 'ClientVersion'
        /// </summary>
        [Fact]
        public void ClientVersionTest()
        {
            // TODO unit test for the property 'ClientVersion'
        }
        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Fact]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Identifier'
        /// </summary>
        [Fact]
        public void IdentifierTest()
        {
            // TODO unit test for the property 'Identifier'
        }
        /// <summary>
        /// Test the property 'Merchantid'
        /// </summary>
        [Fact]
        public void MerchantidTest()
        {
            // TODO unit test for the property 'Merchantid'
        }
        /// <summary>
        /// Test the property 'SubscriptionId'
        /// </summary>
        [Fact]
        public void SubscriptionIdTest()
        {
            // TODO unit test for the property 'SubscriptionId'
        }
        /// <summary>
        /// Test the property 'TxType'
        /// </summary>
        [Fact]
        public void TxTypeTest()
        {
            // TODO unit test for the property 'TxType'
        }

    }

}
