/*
 * CityPay Payment API
 *
 *  This CityPay API is a HTTP RESTful payment API used for direct server to server transactional processing. It provides a number of payment mechanisms including: Internet, MOTO, Continuous Authority transaction processing, 3-D Secure decision handling using RFA Secure, Authorisation, Refunding, Pre-Authorisation, Cancellation/Voids and Completion processing. The API is also capable of tokinsed payments using Card Holder Accounts.  ## Compliance and Security Your application will need to adhere to PCI-DSS standards to operate safely and to meet requirements set out by  Visa and MasterCard and the PCI Security Standards Council. These include  * Data must be collected using TLS version 1.2 using [strong cryptography](#enabled-tls-ciphers). We will not accept calls to our API at   lower grade encryption levels. We regularly scan our TLS endpoints for vulnerabilities and perform TLS assessments   as part of our compliance program. * The application must not store sensitive card holder data (CHD) such as the card security code (CSC) or   primary access number (PAN) * The application must not display the full card number on receipts, it is recommended to mask the PAN   and show the last 4 digits. The API will return this for you for ease of receipt creation * If you are developing a website, you will be required to perform regular scans on the network where you host the   application to meet your compliance obligations * You will be required to be PCI Compliant and the application must adhere to the security standard. Further information   is available from [https://www.pcisecuritystandards.org/](https://www.pcisecuritystandards.org/) * The API verifies that the request is for a valid account and originates from a trusted source using the remote IP   address. Our application firewalls analyse data that may be an attempt to break a large number of security common   security vulnerabilities. 
 *
 * Contact: support@citypay.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = CityPayAPI.Client.OpenAPIDateConverter;

namespace CityPayAPI.Model
{
    /// <summary>
    /// PaylinkCustomParam
    /// </summary>
    [DataContract(Name = "PaylinkCustomParam")]
    public partial class PaylinkCustomParam : IEquatable<PaylinkCustomParam>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaylinkCustomParam" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PaylinkCustomParam() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PaylinkCustomParam" /> class.
        /// </summary>
        /// <param name="fieldType">the type of html5 field, defaults to &#39;text&#39;..</param>
        /// <param name="group">a group the parameter is linked with, allows for grouping with a title..</param>
        /// <param name="label">a label to show alongside the input..</param>
        /// <param name="locked">whether the parameter is locked from entry..</param>
        /// <param name="name">the name of the custom parameter used to converse with the submitter. (required).</param>
        /// <param name="order">an index order for the parameter..</param>
        /// <param name="pattern">a regex pattern to validate the custom parameter with..</param>
        /// <param name="placeholder">a placehold value to display in the input..</param>
        /// <param name="required">whether the field is required..</param>
        /// <param name="value">a default value for the field..</param>
        public PaylinkCustomParam(string fieldType = default(string), string group = default(string), string label = default(string), bool locked = default(bool), string name = default(string), int order = default(int), string pattern = default(string), string placeholder = default(string), bool required = default(bool), string value = default(string))
        {
            // to ensure "name" is required (not null)
            this.Name = name ?? throw new ArgumentNullException("name is a required property for PaylinkCustomParam and cannot be null");
            this.FieldType = fieldType;
            this.Group = group;
            this.Label = label;
            this.Locked = locked;
            this.Order = order;
            this.Pattern = pattern;
            this.Placeholder = placeholder;
            this.Required = required;
            this.Value = value;
        }

        /// <summary>
        /// the type of html5 field, defaults to &#39;text&#39;.
        /// </summary>
        /// <value>the type of html5 field, defaults to &#39;text&#39;.</value>
        [DataMember(Name = "field_type", EmitDefaultValue = false)]
        public string FieldType { get; set; }

        /// <summary>
        /// a group the parameter is linked with, allows for grouping with a title.
        /// </summary>
        /// <value>a group the parameter is linked with, allows for grouping with a title.</value>
        [DataMember(Name = "group", EmitDefaultValue = false)]
        public string Group { get; set; }

        /// <summary>
        /// a label to show alongside the input.
        /// </summary>
        /// <value>a label to show alongside the input.</value>
        [DataMember(Name = "label", EmitDefaultValue = false)]
        public string Label { get; set; }

        /// <summary>
        /// whether the parameter is locked from entry.
        /// </summary>
        /// <value>whether the parameter is locked from entry.</value>
        [DataMember(Name = "locked", EmitDefaultValue = true)]
        public bool Locked { get; set; }

        /// <summary>
        /// the name of the custom parameter used to converse with the submitter.
        /// </summary>
        /// <value>the name of the custom parameter used to converse with the submitter.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// an index order for the parameter.
        /// </summary>
        /// <value>an index order for the parameter.</value>
        [DataMember(Name = "order", EmitDefaultValue = false)]
        public int Order { get; set; }

        /// <summary>
        /// a regex pattern to validate the custom parameter with.
        /// </summary>
        /// <value>a regex pattern to validate the custom parameter with.</value>
        [DataMember(Name = "pattern", EmitDefaultValue = false)]
        public string Pattern { get; set; }

        /// <summary>
        /// a placehold value to display in the input.
        /// </summary>
        /// <value>a placehold value to display in the input.</value>
        [DataMember(Name = "placeholder", EmitDefaultValue = false)]
        public string Placeholder { get; set; }

        /// <summary>
        /// whether the field is required.
        /// </summary>
        /// <value>whether the field is required.</value>
        [DataMember(Name = "required", EmitDefaultValue = true)]
        public bool Required { get; set; }

        /// <summary>
        /// a default value for the field.
        /// </summary>
        /// <value>a default value for the field.</value>
        [DataMember(Name = "value", EmitDefaultValue = false)]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaylinkCustomParam {\n");
            sb.Append("  FieldType: ").Append(FieldType).Append("\n");
            sb.Append("  Group: ").Append(Group).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  Locked: ").Append(Locked).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("  Pattern: ").Append(Pattern).Append("\n");
            sb.Append("  Placeholder: ").Append(Placeholder).Append("\n");
            sb.Append("  Required: ").Append(Required).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PaylinkCustomParam);
        }

        /// <summary>
        /// Returns true if PaylinkCustomParam instances are equal
        /// </summary>
        /// <param name="input">Instance of PaylinkCustomParam to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaylinkCustomParam input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FieldType == input.FieldType ||
                    (this.FieldType != null &&
                    this.FieldType.Equals(input.FieldType))
                ) && 
                (
                    this.Group == input.Group ||
                    (this.Group != null &&
                    this.Group.Equals(input.Group))
                ) && 
                (
                    this.Label == input.Label ||
                    (this.Label != null &&
                    this.Label.Equals(input.Label))
                ) && 
                (
                    this.Locked == input.Locked ||
                    this.Locked.Equals(input.Locked)
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Order == input.Order ||
                    this.Order.Equals(input.Order)
                ) && 
                (
                    this.Pattern == input.Pattern ||
                    (this.Pattern != null &&
                    this.Pattern.Equals(input.Pattern))
                ) && 
                (
                    this.Placeholder == input.Placeholder ||
                    (this.Placeholder != null &&
                    this.Placeholder.Equals(input.Placeholder))
                ) && 
                (
                    this.Required == input.Required ||
                    this.Required.Equals(input.Required)
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FieldType != null)
                    hashCode = hashCode * 59 + this.FieldType.GetHashCode();
                if (this.Group != null)
                    hashCode = hashCode * 59 + this.Group.GetHashCode();
                if (this.Label != null)
                    hashCode = hashCode * 59 + this.Label.GetHashCode();
                hashCode = hashCode * 59 + this.Locked.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                hashCode = hashCode * 59 + this.Order.GetHashCode();
                if (this.Pattern != null)
                    hashCode = hashCode * 59 + this.Pattern.GetHashCode();
                if (this.Placeholder != null)
                    hashCode = hashCode * 59 + this.Placeholder.GetHashCode();
                hashCode = hashCode * 59 + this.Required.GetHashCode();
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
