name: Build

on:
  release:
    types: [published]
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        use-multiple-toolkits: true
    - name: Install dotnet-targeting-pack-3.1
      run: sudo apt-get install dotnet-targeting-pack-3.1
    - name: Install aspnetcore-targeting-pack-3.1
      run: sudo apt-get install aspnetcore-targeting-pack-3.1
    - name: Install .NET Core 3.1
      run: sudo apt-get install dotnet-sdk-3.1
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release --no-build
