name: Build

on:
  release:
    types: [published]
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'
    - name: Test
      run: dotnet test
      env:
        CP_CLIENT_ID: ${{secrets.CP_CLIENT_ID}}
        CP_MERCHANT_ID: ${{secrets.CP_MERCHANT_ID}}
        CP_LICENCE_KEY: ${{secrets.CP_LICENCE_KEY}}
